### ISSUE TITLE
how to add @ant-design/react-native tab bar ? 

### ISSUE THREAD

**Issue by elaoshi** [xuyuanxiang/UMIRNExample#2]
for tab bar in  @ant-design/react-native ,
Could you give me an example ? Thanks

**Comment by xuyuanxiang** [comment]
> for tab bar in @ant-design/react-native ,
> Could you give me an example ? Thanks

First, install `@react-navigation/bottom-tabs`:

```npm
yarn add @react-navigation/bottom-tabs
```

Then, you can nested tab navigation in any pages as your wish.

I nested two tab navigations in this case [UMIRNExample#feature/tab-navigation](https://github.com/xuyuanxiang/UMIRNExample/tree/feature/navigation-tabs):

- [pages/index](https://github.com/xuyuanxiang/UMIRNExample/tree/feature/navigation-tabs/pages/index.js)
- [pages/user](https://github.com/xuyuanxiang/UMIRNExample/tree/feature/navigation-tabs/pages/user.js)

For more details: [react-navitaion#tab-based-navigation](https://reactnavigation.org/docs/tab-based-navigation).
